package com.wpt.risk.dal.dao;

import com.wpt.risk.dal.pojo.WUser;
import org.apache.ibatis.annotations.Param;

public interface WUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated
     */
    int insert(WUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated
     */
    int insertSelective(WUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated
     */
    WUser selectByPrimaryKey(Integer id);

    public WUser selectByUserId(@Param("uname") String uname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WUser record);
}